"use client";

import { useState } from "react";
import { tasks, interns } from "./demoData";
import { ActionButton, EmptyModal, EvaluationCard, Panel, Stat, TaskBoard } from "./WorkspaceShell";

export default function SupervisorView() {
  const [showAnnouncement, setShowAnnouncement] = useState(false);
  const [sent, setSent] = useState(false);
  return <><section className="welcome-row role-welcome"><div><p className="eyebrow">Monday, August 10, 2026</p><h1>Good morning, Mia <span className="wave">✦</span></h1><p className="subtitle">Your team has 12 active tasks that need a little momentum.</p></div><ActionButton onClick={() => setShowAnnouncement(true)} icon="message">New announcement</ActionButton></section><section className="stats-grid"><Stat label="Assigned interns" value="12" note="Across 2 programs" /><Stat label="Pending tasks" value="15" note="4 due this week" tone="coral" /><Stat label="Completed tasks" value="80" note="↑ 18% this month" tone="blue" /><Stat label="Evaluations due" value="7 / 12" note="Submit by Friday" tone="orange" /></section><Panel title="Team task board" subtitle="Create parent tasks, collaborate, and track delivery." icon="check" action={<span className="premium-tag panel-premium">PREMIUM TOOLS</span>}><TaskBoard initialTasks={tasks} canManage /></Panel><div className="role-layout supervisor-bottom"><EvaluationCard canEdit /><Panel title="Your interns" subtitle="Open a profile to review their work." icon="users" tone="peach"><div className="compact-people">{interns.slice(0, 3).map((intern) => <div className="compact-person" key={intern.name}><span className="avatar small">{intern.initials}</span><div><strong>{intern.name}</strong><span>{intern.progress}% task progress · {intern.attendance} attendance</span></div><button className="row-action">→</button></div>)}</div></Panel></div>{showAnnouncement && <EmptyModal title="Post an announcement" description="Reach your intern team instantly." onClose={() => setShowAnnouncement(false)}><form className="simple-form" onSubmit={(event) => { event.preventDefault(); setShowAnnouncement(false); setSent(true); }}><label>Announcement<input placeholder="e.g. Please submit your weekly log by Friday" required /></label><label>Send to<select defaultValue="All assigned interns"><option>All assigned interns</option><option>Northstar Digital interns</option><option>Brightline Labs interns</option></select></label><div className="modal-actions"><ActionButton variant="secondary" onClick={() => setShowAnnouncement(false)} icon={null}>Cancel</ActionButton><ActionButton icon="message">Send announcement</ActionButton></div></form></EmptyModal>}{sent && <button className="toast" onClick={() => setSent(false)}>Announcement sent to 12 interns <span>✓</span></button>}</>;
}
